# 使用参考 https://zhuanlan.zhihu.com/p/54266685
# 使用参考 https://blog.csdn.net/weixin_36242811/article/details/108611523

# demo-01
get http://localhost:8080/get

# demo-02

###
get http://localhost:8080/test

###
post http://localhost:8080/test

### 
delete http://localhost:8080/test


# demo-04

###
get http://localhost:8080/user/test

###
post http://localhost:8080/user/test

### 
delete http://localhost:8080/user/test

###
get http://localhost:8080/good/test

###
post http://localhost:8080/good/test

### 
delete http://localhost:8080/good/test

# index-05
### 
get http://localhost:8080/index/index


# index-06
### 
get http://localhost:8080/query?a=1&b=2


###
POST http://localhost:8080/post HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo
&password=bar


### 

POST http://localhost:8080/post HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--




###
POST http://localhost:8090/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo
&password=bar


###
GET http://localhost:8090/get-info?name=foo HTTP/1.1